### ISSUE TITLE
Login system doesn't work

### ISSUE THREAD

**Issue by KingCharlesVI** [KingCharlesVI/tunedtv-website#41]
Login system developed according to [this youtube tutorial](https://www.youtube.com/watch?v=gCo6JqGMi30) doesn't work.
Doesn't seem to be communicating with database correctly (no records are being written/read).

**As of merge pull request #68 submission of the sign up form gives error=stmtfailed in the url**

**Comment by WangNok** [comment]
Hi !

Can I see the database structure ? (Photo)

Also if you want I can write login & signup system or account system from scratch for this site. Just let me know from here (reply) or from here : https://yasarkaancan.com/contact-me

**Comment by KingCharlesVI** [comment]
As of merge pull request #74 once logged in, visitors get ERR_SSL_PROTOCOL_ERROR (in Chrome)
